const data = [
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 26,
        "externalid": "5de81d15dd3e2d00164eb884",
        "description": "Main entrance",
        "lat": "9.975505144718667",
        "lon": "-84.7496693173604",
        "identifier": "entrada_principal",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "11C1A",
      "minor":1
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 25,
        "externalid": "5df081fbcfc8cf0016d9eaa5",
        "description": "North men's hall",
        "lat": "9.975781813984241",
        "lon": "-84.74951280338281",
        "identifier": "pasillo_hombres_norte",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "157C9",
      "minor":2
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 26,
        "externalid": "5de81d15dd3e2d00164eb884",
        "description": "Main entrance",
        "lat": "9.975505144718667",
        "lon": "-84.7496693173604",
        "identifier": "entrada_principal",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "4B07F",
      "minor":3
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 29,
        "externalid": "5df0825d1bb18c001609e8e4",
        "description": "South men hall",
        "lat": "9.975585803768695",
        "lon": "-84.74957142229992",
        "identifier": "pasillo_hombres_sur",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "4CCE0",
      "minor":4
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 36,
        "externalid": "5fa997c38b994d0016570500",
        "description": "Men Bathroom",
        "lat": "9.975833451834262",
        "lon": "-84.7495422090353",
        "identifier": "bathroom_men",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "4ECF7",
      "minor":5
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 30,
        "externalid": "5df0831fc03d5f0016312c3a",
        "description": "South women hall",
        "lat": "9.975549779331416",
        "lon": "-84.74944483997986",
        "identifier": "pasillo_mujeres_sur",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "64F16",
      "minor":6
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 25,
        "externalid": "5df081fbcfc8cf0016d9eaa5",
        "description": "North men's hall",
        "lat": "9.975781813984241",
        "lon": "-84.74951280338281",
        "identifier": "pasillo_hombres_norte",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "6AFB7",
      "minor":7
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 25,
        "externalid": "5df081fbcfc8cf0016d9eaa5",
        "description": "North men's hall",
        "lat": "9.975781813984241",
        "lon": "-84.74951280338281",
        "identifier": "pasillo_hombres_norte",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "95A86",
      "minor":8
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 28,
        "externalid": "5df082b1cfc8cf0016d9eac7",
        "description": "North women hall",
        "lat": "9.975746391999877",
        "lon": "-84.74938288507441",
        "identifier": "pasillo_mujeres_norte",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "C4ABF",
      "minor":9
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 43,
        "externalid": "5fa99747be651400161c08ad",
        "description": "Women Bathroom",
        "lat": "9.975769678754617",
        "lon": "-84.74932601714112",
        "identifier": "bathroom_women",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "D1E9F",
      "minor":10
    },
    {
      "point": {
        "Asset_Position_History": [],
        "Asset_Position_Summary": [],
        "Asset_Position_Temporal": [],
        "Beacon_Position_History": [],
        "Beacon_Position_Summary": [],
        "BeaconPoints": [],
        "Gateways": [],
        "GatewayBeacons": [],
        "Person_Position_History": [],
        "Person_Position_Summary": [],
        "Person_Position_Temporal": [],
        "SubCatergory": null,
        "id": 37,
        "externalid": "5e4ef9f51fa49c0016f0cf11",
        "description": "Emergency exit Medicine Women",
        "lat": "9.974977451163355",
        "lon": "-84.74987912694017",
        "identifier": "salida_de_emergencias_medicina_mujeres",
        "subcategoryid": 32,
        "ticketpointid": null
      },
      "shortid": "DFD47",
      "minor":11
    }
  ]

  export default data;